version: '3.7'

services:

  cortex:
    image: cortexproject/cortex:v0.1.0
    ports:
      - "9009:9009"
    command: "-config.file=/etc/single-process-config.yaml"
    volumes:
      - "./cortex/single-process-config.yaml:/etc/single-process-config.yaml"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - "./var/grafana/grafana_data:/var/lib/grafana"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
